config/routes.rb
Rails.application.routes.draw do
  resources :books
  get 'sscs/index'

  get 'sscs/new'

  get 'sscs/edit'

  get 'sscs/show'

  get 'sscs/destroy'

  resources :members
  resources :members
  resources :members
  resources :members
  root 'homes#index'

  devise_for :users
match ':controller(/:action(/:id))', :via=>[:get,:post,:patch]

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/ssc.rb
class Ssc < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
#layout false

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
    @book_count= Book.count + 1
  end

  # GET /books/1/edit
  def edit
     @book_count= Book.count + 1
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:sr_no, :name, :copy, :images)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    if signed_in?
      redirect_to(:controller=>'members',:action=>'index')


    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!
layout false
  # GET /members
  # GET /members.json
  def index
    @members = Member.paginate(:page => params[:page], :per_page => 3)
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:membership_id, :name, :father_name, :husband, :village, :postOffice, :thana, :district, :present_address, :district, :phone, :acknowledgement_name, :acknowledgement_relation, :date_of_enrollment, :roll, :date_of_past_enrollment, :date_of_cancel, :cancel_roll, :status, :date_of_membership, :created_by_id, :updated_by_id)
    end
end

app/controllers/sscs_controller.rb
class SscsController < ApplicationController
  def index
    @ssc = Ssc.all
  end

  def new
    @ssc = Ssc.new
    
  end

  def edit
    #@ssc =Ssc.find(params[:id])
     
     end
     
     def create
        @ssc = Ssc.new(ssc_params)
        if @ssc.save
          flash[:notice]="created success fully"
          redirect_to(:controller=>'sscs', :action=> 'index')
        else 
          render 'new'
        end
     end
     
    
  def update
    @ssc = Ssc.update_attributes(ssc_params)
  end

  def show
    @ssc =Ssc.find_by_id(params[:id])
  end

  def destroy
    @ssc =Ssc.find(params[:id])
    @ssc.destroy
    flash[:notice]= "destroyed"
  end
  private
  
  def ssc_params
    params.require(:ssc).permit(:membership_id,:result,:year,:board,:created_by_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/sscs_helper.rb
module SscsHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sr_no %><br>
    <%= f.select(:sr_no, 1..@book_count )%>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :copy %><br>
    <%= f.number_field :copy %>
  </div>
  <div class="field">
    <%= f.label :images %><br>
    <%= f.text_field :images %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<table  width = 500px border = 5px>
  <thead>
    <tr>
      <th>Sr no</th>
      <th>Name</th>
      <th>Copy</th>
      <th>Images</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.sr_no %></td>
        <td><%= book.name %></td>
        <td><%= book.copy %></td>
        <td><%= image_tag book.images, :width=>50 ,:height=>50%> 
  <%=link_to 'show_image',image_path(book.images)%></td>
        <td ><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sr no:</strong>
  <%= @book.sr_no %>
</p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Copy:</strong>
  <%= @book.copy %>
</p>

<p>
  <strong>Images:</strong>
 <%= image_tag @book.images, :width=>50 ,:height=>50 %> 
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>
 <%#=link_to "logout", destroy_user_session_path ,method: :delete %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DBAR</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <% if user_signed_in? %>
  <p>welcome, signed in as <%=current_user.email%></p>
<%= link_to "logout", destroy_user_session_path ,method: :delete%>
<%else%>   
<%= link_to "login",  new_user_session_path %>
<%end%>
  <table width = 800px >
<tr bgcolor = "gray" ><td align="center" colspan = "2"><h2> Samle page </h2></td>

</tr>
<tr>
<td>
<table width =150px height = 300px bgcolor = gray border = '1px' >
<tr><td style="text-align:center;"> Admin Pannel</td> </br>
 <tr><td style="text-align:center;text-decoration:none"><a href="#" >Member</a></td></tr>
 <tr><td align="center"><a href="#" >Library</a></td></tr>
 <tr><td align="center"><a href="#" >User</a></td></tr>
 <tr><td align="center"><a href="#" >Account List</a></td></tr>
<tr><td align="center"><a href="#" >Voter List</a></td></tr>
</tr>
</table>
</td>
<td>
<table width =600px height = 400px >
<tr><td> <%= yield %></td></tr>
</table>
</td>
</tr>
<table>

<%#= yield %>

</body>
</html>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <p><h3>Personal info</h3></p>
    <%= f.label :membership_id %><br>
    <%= f.number_field :membership_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :placeholder=>'enter yor name' %>
  </div>
  <div class="field">
    <%= f.label :father_name %><br>
    <%= f.text_field :father_name %>
  </div>
  <div class="field">
    <%= f.label :husband %><br>
    <%= f.text_field :husband,:placeholder=>'optional'  %>
  </div>
  <div class="field">
      <p><h3>Permanent address</h3></p>
    <%= f.label :village %><br>
    <%= f.text_field :village %>
  </div>
  <div class="field">
    <%= f.label :postOffice %><br>
    <%= f.text_field :postOffice %>
  </div>
  <div class="field">
    <%= f.label :thana %><br>
    <%= f.text_field :thana %>
  </div>
  <div class="field">
    <%= f.label :district %><br>
    <%= f.text_field :district %>
  </div>
  <div class="field">
      <p><h3>Present address </h3></p>
    <%= f.label :present_address %><br>
    <%= f.text_area :present_address %>
  </div>
  <div class="field">
    <%= f.label :district %><br>
    <%= f.text_field :district %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
      <p><h3>Enrollment info </h3></p>
    <%= f.label :acknowledgement_name %><br>
    <%= f.text_field :acknowledgement_name %>
  </div>
  <div class="field">
    <%= f.label :acknowledgement_relation %><br>
    <%= f.text_field :acknowledgement_relation %>
  </div>
  <div class="field">
    <%= f.label :date_of_enrollment %><br>
    <%= f.text_field :date_of_enrollment %>
  </div>
  <div class="field">
    <%= f.label :roll %><br>
    <%= f.number_field :roll %>
  </div>
  <div class="field">
    <%= f.label :date_of_past_enrollment %><br>
    <%= f.text_field :date_of_past_enrollment %>
  </div>
  <div class="field">
    <%= f.label :date_of_cancel %><br>
    <%= f.text_field :date_of_cancel %>
  </div>
  <div class="field">
    <%= f.label :cancel_roll %><br>
    <%= f.number_field :cancel_roll %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :date_of_membership %><br>
    <%= f.text_field :date_of_membership %>
  </div>
  <div class="field">
      <p><h3>Other info </h3></p>
    <%= f.label :created_by_id %><br>
    <%= f.number_field :created_by_id %>
  </div>
  <div class="field">
    <%= f.label :updated_by_id %><br>
    <%= f.number_field :updated_by_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style= "text-shadow: #6EB7FF;">Listing Members</h1>

<table width = 500px border = 5px>
  <thead>
    <tr style = "background-color:goldenrod">
      <th>Membership</th>
      <th>Name</th>
      <th>Present address</th>
      <th>District</th>
      <th>Phone</th>
     
      <th>Status</th>
     
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr style = 'color:blueviolet;'>
        <td><%= member.membership_id %></td>
        <td><%= member.name %></td>
        
        <td><%= member.present_address %></td>
        <td><%= member.district %></td>
        <td><%= member.phone %></td>
        
        <td><%= member.status %></td>
        
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>
<br/>
<%= will_paginate @members %>
<%=link_to 'micropost', "https://www.youtube.com"%>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Membership:</strong>
  <%= @member.membership_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Father name:</strong>
  <%= @member.father_name %>
</p>

<p>
  <strong>Husband:</strong>
  <%= @member.husband %>
</p>

<p>
  <strong>Village:</strong>
  <%= @member.village %>
</p>

<p>
  <strong>Postoffice:</strong>
  <%= @member.postOffice %>
</p>

<p>
  <strong>Thana:</strong>
  <%= @member.thana %>
</p>

<p>
  <strong>District:</strong>
  <%= @member.district %>
</p>

<p>
  <strong>Present address:</strong>
  <%= @member.present_address %>
</p>

<p>
  <strong>District:</strong>
  <%= @member.district %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @member.phone %>
</p>

<p>
  <strong>Acknowledgement name:</strong>
  <%= @member.acknowledgement_name %>
</p>

<p>
  <strong>Acknowledgement relation:</strong>
  <%= @member.acknowledgement_relation %>
</p>

<p>
  <strong>Date of enrollment:</strong>
  <%= @member.date_of_enrollment %>
</p>

<p>
  <strong>Roll:</strong>
  <%= @member.roll %>
</p>

<p>
  <strong>Date of past enrollment:</strong>
  <%= @member.date_of_past_enrollment %>
</p>

<p>
  <strong>Date of cancel:</strong>
  <%= @member.date_of_cancel %>
</p>

<p>
  <strong>Cancel roll:</strong>
  <%= @member.cancel_roll %>
</p>

<p>
  <strong>Status:</strong>
  <%= @member.status %>
</p>

<p>
  <strong>Date of membership:</strong>
  <%= @member.date_of_membership %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @member.created_by_id %>
</p>

<p>
  <strong>Updated by:</strong>
  <%= @member.updated_by_id %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/sscs/destroy.html.erb
<h1>Sscs#destroy</h1>
<p>Find me in app/views/sscs/destroy.html.erb</p>
<%= flash[:notice] %>
<%= link_to 'back',{:action=>'index'} %>

app/views/sscs/edit.html.erb
<h1>Sscs#edit</h1>
<p>Find me in app/views/sscs/edit.html.erb</p>

app/views/sscs/index.html.erb
<h1>Sscs#index</h1>
<p>Find me in app/views/sscs/index.html.erb</p>
<%@ssc.each do |s|%>
<table width = 500px border = 5px>
    <tr style = "background-color:goldenrod ">
        <td>Member_id</td>
        <td>Result</td>
        <td>year</td>
        <td>board</td>
         <td>created_by</td>
           <td>actions</td>
    </tr>
    <tr style = 'color:blueviolet;'>    
<td><%= s.membership_id%></td>
<td><%= s.result %></td>
<td><%= s.year %></td>
<td><%= s.board%></td>
<td> <%=s.created_by_id %></td>
    
    <td>
<%= link_to 'show',{:action=>'show',:id=>s.id} %>
<%= link_to 'edit',{:action=>'edit',:id=>s.id}%>
<%= link_to 'destroy',{:action=>'destroy',:id=>s.id}%>

   </td> </tr></table>
<%end%>

app/views/sscs/new.html.erb
<h1>Sscs#new</h1>
<p>Find me in app/views/sscs/new.html.erb</p>
<%=form_for @ssc,:url=>{:action=> 'create'} do |s|%>

  <%= s.label :membership_id %>
<%= s.text_field :membership_id %> <br>
<%= s.label :result %>
<%=  s.select(:result,['first','second'] )%><br>

  <%= s.label :year %>
<%= s.text_field :year %><br>

<%= s.label :board %>
<%= s.text_field :board %>
<%= s.label :created_by_id %>
<%= s.text_field :created_by_id %>
<%= s.submit %>
<%end%>

app/views/sscs/show.html.erb
<h1>Sscs#show</h1>
<p>Find me in app/views/sscs/show.html.erb</p>

<table>
    <tr style = "background-color:gray ">
        <td>Member_id</td>
        <td>Result</td>
        <td>year</td>
        <td>board</td>
         <td>created_by</td>
    </tr>
    <tr>    
<td><%= @ssc.membership_id%></td>
<td><%= @ssc.result %></td>
<td><%= @ssc.year %></td>
<td><%= @ssc.board%></td>
<td> created_by_id</td>
    
    <td>
<%= link_to 'back',{:action=>'index'} %>

   </td> </tr></table>